output "resource_group" {
  value       = azurerm_resource_group.main.name
  description = "The resource group."
}

output "application_name" {
  value       = module.application.application_caf_name
  description = "The application name generated by the Azure Cloud Adoption Framework."
}

output "spring_apps_service_name" {
  value       = module.application.spring_apps_service_name
  description = "Azure Spring Apps service name"
}

output "afd_endpoint_hostname"{
  value       = module.front_door.afd_endpoint_hostname
  description = "Azure Front Door hostname"
}
